INSERT INTO listening_tests (id, title, audio_url, transcript, difficulty, time_limit) VALUES 
(2, 'Food', 'https://listenaminute.com/f/food.mp3', 'Isn''t food one of life''s greatest pleasures? Do you know anyone who doesn''t like food? I don''t. There is so much delicious food in the world. You could spend a whole lifetime eating a different dish every day. What''s the tastiest food in the world? This is a very difficult question to answer. My taste in food keeps changing. Sometimes my favourite is a dessert, but then I change my mind and go for a spicy curry. It''s great that countries have so many different dishes. Do you think your national dish is best? Nowadays we have to be careful about what we eat. Fast food is not good for us. We need to focus more on healthy food. Maybe we have to be more careful in the future. Make sure the food you eat is good for you.', 'easy', 5),
(3, 'Crime Report Form', 'https://listenaminute.com/c/crime.mp3', 'Officer: Police Station, Officer Jones speaking.\nLouise: Hello, I would like to report a theft. I had some things stolen out of my bag yesterday.\nOfficer: I am sorry to hear that. Right, so I will need to take a few details. Can I start with your name?\nLouise: Louise Taylor.\nOfficer: OK, thank you. And can I have your address?\nLouise: It is Apartments 3, 40 Lake Street.\nOfficer: Lake Street?\nLouise: Yes, that is right.\nOfficer: And your phone number?\nLouise: 07787 554321.\nOfficer: Right. So, can you tell me what happened?\nLouise: Well, I was in the city centre yesterday afternoon, looking for a coat. I had been in a few shops and then I went to a cafe. When I went to pay for my coffee, I realised my purse was missing.\nOfficer: Did you leave it in the shop?\nLouise: No, I am sure I had it when I went into the cafe. Someone must have taken it from my bag while I was sitting there.', 'easy', 10);

INSERT INTO questions (listening_test_id, module, question_type, question_text, options_json, correct_answer, explanation, position) VALUES
(2, 'listening', 'fill_blank', 'Food is described as one of life''s greatest ________.', NULL, 'pleasures', 'The speaker says: "Isn''t food one of life''s greatest pleasures?"', 1),
(2, 'listening', 'mcq', 'How much delicious food does the speaker say exists?', '["Not much", "So much", "Just enough"]', 'So much', 'The speaker says: "There is so much delicious food in the world."', 2),
(2, 'listening', 'fill_blank', 'You could spend a whole ________ eating a different dish every day.', NULL, 'lifetime', 'The speaker says: "You could spend a whole lifetime eating a different dish every day."', 3),
(2, 'listening', 'mcq', 'What does the speaker sometimes go for after changing their mind from dessert?', '["A salad", "A spicy curry", "A pizza"]', 'A spicy curry', 'The speaker says: "...then I change my mind and go for a spicy curry."', 4),
(2, 'listening', 'fill_blank', 'The speaker says their taste in food keeps ________.', NULL, 'changing', 'The speaker says: "My taste in food keeps changing."', 5),
(2, 'listening', 'mcq', 'According to the speaker, what is NOT good for us?', '["Healthy food", "Fast food", "Home cooking"]', 'Fast food', 'The speaker says: "Fast food is not good for us."', 6),
(2, 'listening', 'fill_blank', 'We need to focus more on ________ food.', NULL, 'healthy', 'The speaker says: "We need to focus more on healthy food."', 7),
(2, 'listening', 'mcq', 'What does the speaker say is a very difficult question?', '["What is the healthiest food?", "What is the tastiest food in the world?", "What is the cheapest food?"]', 'What is the tastiest food in the world?', 'The speaker says: "What''s the tastiest food in the world? This is a very difficult question to answer."', 8),
(2, 'listening', 'fill_blank', 'It''s great that countries have so many different ________.', NULL, 'dishes', 'The speaker says: "It''s great that countries have so many different dishes."', 9),
(2, 'listening', 'fill_blank', 'Make sure the food you eat is good for ________.', NULL, 'you', 'The speaker says: "Make sure the food you eat is good for you."', 10);

INSERT INTO questions (listening_test_id, module, question_type, question_text, options_json, correct_answer, explanation, position) VALUES
(3, 'listening', 'fill_blank', 'The caller''s name is Louise ________.', NULL, 'Taylor', 'Louise introduces herself as Louise Taylor.', 1),
(3, 'listening', 'fill_blank', 'She lives at 40 ________ Street.', NULL, 'Lake', 'Louise gives her address as Apartments 3, 40 Lake Street.', 2),
(3, 'listening', 'fill_blank', 'She went to the city centre to look for a ________.', NULL, 'coat', 'Louise states: "I was in the city centre yesterday afternoon, looking for a coat."', 3),
(3, 'listening', 'mcq', 'Where did Louise realise her purse was missing?', '["In a shop", "In a cafe", "At the bus stop"]', 'In a cafe', 'She says: "When I went to pay for my coffee, I realised my purse was missing."', 4),
(3, 'listening', 'mcq', 'What does Louise think happened to her purse?', '["She dropped it in the street", "Someone stole it from her bag", "She left it at home"]', 'Someone stole it from her bag', 'She says: "Someone must have taken it from my bag while I was sitting there."', 5);

