INSERT INTO listening_tests (id, title, audio_url, transcript, difficulty, time_limit) VALUES 
(2, 'Cambridge IELTS 13 - Cookery Classes', 'https://listenaminute.com/c/cooking.mp3', 'Official: Hello, Tourist Information Centre, Mike speaking, how can I help you?\nWoman: Oh, hi. I wanted to find out about cookery classes. I believe there are some one-day classes for tourists?\nOfficial: Well, they are open to everyone, but tourists find them very useful. Right, let me give you some details of what is available. There are several classes. One very popular one is at the Food Studio.\nWoman: OK.\nOfficial: They focus on seasonal products, and as well as teaching you how to cook them, they also show you how to choose them.\nWoman: Right, that sounds good. How big are the classes?\nOfficial: I am not sure exactly, but they will be quite small.\nWoman: And could I get a private lesson there?\nOfficial: I think so... let me check... yes, they do offer those. Though in fact most of the people who attend the classes find it is a nice way of getting to know one another.\nWoman: I suppose it must be, yes.\nOfficial: And this company has a special deal for clients where they offer a discount of 20 percent if you return for a further class.\nWoman: OK. But you said there were several classes?\nOfficial: That is right. Another one you might be interested in is Bond''s Cookery School. They are quite new, they just opened six months ago, but I have heard good things about them. They concentrate on teaching you to prepare healthy food, and they have quite a lot of specialist staff.', 'medium', 10),
(3, 'Cambridge IELTS 14 - Crime Report Form', 'https://listenaminute.com/c/crime.mp3', 'Officer: Police Station, Officer Jones speaking.\nLouise: Hello, I would like to report a theft. I had some things stolen out of my bag yesterday.\nOfficer: I am sorry to hear that. Right, so I will need to take a few details. Can I start with your name?\nLouise: Louise Taylor.\nOfficer: OK, thank you. And can I have your address?\nLouise: It is Apartments 3, 40 Lake Street.\nOfficer: Lake Street?\nLouise: Yes, that is right.\nOfficer: And your phone number?\nLouise: 07787 554321.\nOfficer: Right. So, can you tell me what happened?\nLouise: Well, I was in the city centre yesterday afternoon, looking for a coat. I had been in a few shops and then I went to a cafe. When I went to pay for my coffee, I realised my purse was missing.\nOfficer: Did you leave it in the shop?\nLouise: No, I am sure I had it when I went into the cafe. Someone must have taken it from my bag while I was sitting there.', 'easy', 10);

INSERT INTO questions (listening_test_id, module, question_type, question_text, options_json, correct_answer, explanation, position) VALUES
(2, 'listening', 'fill_blank', 'The first cooking class is at the ________ Studio.', NULL, 'Food', 'The official states: "One very popular one is at the Food Studio."', 1),
(2, 'listening', 'fill_blank', 'They show you how to ________ seasonal products as well as cook them.', NULL, 'choose', 'The official says: "...as well as teaching you how to cook them, they also show you how to choose them."', 2),
(2, 'listening', 'mcq', 'What special deal does the Food Studio offer?', '["20% discount on first class", "20% discount for returning", "Free recipe book"]', '20% discount for returning', 'The official says they offer a discount of 20 percent if you return for a further class.', 3),
(2, 'listening', 'fill_blank', 'Bond''s Cookery School opened ________ months ago.', NULL, 'six', 'The official states: "...they just opened six months ago..."', 4),
(2, 'listening', 'mcq', 'What is the main focus of Bond''s Cookery School?', '["Baking desserts", "Preparing healthy food", "Cooking local dishes"]', 'Preparing healthy food', 'The official says they concentrate on teaching you to prepare healthy food.', 5);

INSERT INTO questions (listening_test_id, module, question_type, question_text, options_json, correct_answer, explanation, position) VALUES
(3, 'listening', 'fill_blank', 'The caller''s name is Louise ________.', NULL, 'Taylor', 'Louise introduces herself as Louise Taylor.', 1),
(3, 'listening', 'fill_blank', 'She lives at 40 ________ Street.', NULL, 'Lake', 'Louise gives her address as Apartments 3, 40 Lake Street.', 2),
(3, 'listening', 'fill_blank', 'She went to the city centre to look for a ________.', NULL, 'coat', 'Louise states: "I was in the city centre yesterday afternoon, looking for a coat."', 3),
(3, 'listening', 'mcq', 'Where did Louise realise her purse was missing?', '["In a shop", "In a cafe", "At the bus stop"]', 'In a cafe', 'She says: "When I went to pay for my coffee, I realised my purse was missing."', 4),
(3, 'listening', 'mcq', 'What does Louise think happened to her purse?', '["She dropped it in the street", "Someone stole it from her bag", "She left it at home"]', 'Someone stole it from her bag', 'She says: "Someone must have taken it from my bag while I was sitting there."', 5);
