INSERT INTO listening_tests (id, title, audio_url, transcript, difficulty, time_limit) VALUES 
(2, 'Food', 'https://listenaminute.com/f/food.mp3', 'Isn''t food one of life''s greatest pleasures? Do you know anyone who doesn''t like food? I don''t. There is so much delicious food in the world. You could spend a whole lifetime eating a different dish every day. What''s the tastiest food in the world? This is a very difficult question to answer. My taste in food keeps changing. Sometimes my favourite is a dessert, but then I change my mind and go for a spicy curry. It''s great that countries have so many different dishes. Do you think your national dish is best? Nowadays we have to be careful about what we eat. Fast food is not good for us. We need to focus more on healthy food. Maybe we have to be more careful in the future. Make sure the food you eat is good for you.', 'easy', 5),
(3, 'Crime', 'https://listenaminute.com/c/crime.mp3', 'Why do we have crime? When will it all stop? It''s sad that there is so much crime in our society. It hurts so many people. Most people in the world just want to live happily and be good neighbours. Why do some people turn to crime? Money is a big reason. Many criminals pickpocket, steal, kidnap, or even kill people to get money. There are many terrible crimes in the world. Perhaps the worst is ethnic cleansing. This is a crime against humanity. Many people are killed because of their colour or religion. People who commit this crime rarely go to prison. Have you ever been a victim of crime?', 'easy', 10);

INSERT INTO questions (listening_test_id, module, question_type, question_text, options_json, correct_answer, explanation, position) VALUES
(2, 'listening', 'fill_blank', 'Food is described as one of life''s greatest ________.', NULL, 'pleasures', 'The speaker says: "Isn''t food one of life''s greatest pleasures?"', 1),
(2, 'listening', 'mcq', 'How much delicious food does the speaker say exists?', '["Not much", "So much", "Just enough"]', 'So much', 'The speaker says: "There is so much delicious food in the world."', 2),
(2, 'listening', 'fill_blank', 'You could spend a whole ________ eating a different dish every day.', NULL, 'lifetime', 'The speaker says: "You could spend a whole lifetime eating a different dish every day."', 3),
(2, 'listening', 'mcq', 'What does the speaker sometimes go for after changing their mind from dessert?', '["A salad", "A spicy curry", "A pizza"]', 'A spicy curry', 'The speaker says: "...then I change my mind and go for a spicy curry."', 4),
(2, 'listening', 'fill_blank', 'The speaker says their taste in food keeps ________.', NULL, 'changing', 'The speaker says: "My taste in food keeps changing."', 5),
(2, 'listening', 'mcq', 'According to the speaker, what is NOT good for us?', '["Healthy food", "Fast food", "Home cooking"]', 'Fast food', 'The speaker says: "Fast food is not good for us."', 6),
(2, 'listening', 'fill_blank', 'We need to focus more on ________ food.', NULL, 'healthy', 'The speaker says: "We need to focus more on healthy food."', 7),
(2, 'listening', 'mcq', 'What does the speaker say is a very difficult question?', '["What is the healthiest food?", "What is the tastiest food in the world?", "What is the cheapest food?"]', 'What is the tastiest food in the world?', 'The speaker says: "What''s the tastiest food in the world? This is a very difficult question to answer."', 8),
(2, 'listening', 'fill_blank', 'It''s great that countries have so many different ________.', NULL, 'dishes', 'The speaker says: "It''s great that countries have so many different dishes."', 9),
(2, 'listening', 'fill_blank', 'Make sure the food you eat is good for ________.', NULL, 'you', 'The speaker says: "Make sure the food you eat is good for you."', 10);

INSERT INTO questions (listening_test_id, module, question_type, question_text, options_json, correct_answer, explanation, position) VALUES
(3, 'listening', 'fill_blank', 'It''s sad that there is so much crime in our ________.', NULL, 'society', 'The speaker says: "It''s sad that there is so much crime in our society."', 1),
(3, 'listening', 'mcq', 'What do most people in the world want to be?', '["Rich", "Good neighbours", "Famous"]', 'Good neighbours', 'The speaker says: "Most people in the world just want to live happily and be good neighbours."', 2),
(3, 'listening', 'fill_blank', 'Money is a big ________ why people turn to crime.', NULL, 'reason', 'The speaker states: "Why do some people turn to crime? Money is a big reason."', 3),
(3, 'listening', 'mcq', 'What do criminals NOT do to get money, according to the transcript?', '["Pickpocket", "Kidnap", "Work hard"]', 'Work hard', 'The speaker lists: "pickpocket, steal, kidnap, or even kill people to get money."', 4),
(3, 'listening', 'mcq', 'What does the speaker consider perhaps the worst crime?', '["Kidnapping", "Stealing", "Ethnic cleansing"]', 'Ethnic cleansing', 'The speaker says: "Perhaps the worst is ethnic cleansing."', 5);

